variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GET_SOURCES_ATTEMPTS: 3

default:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
    - ./install.sh
    - make setup
  after_script:
    - make reset
    - make clean
  
checkin_test:
  only:
    - pushes
  script:
    - cd ./spdk/app/nvmf_tgt; make; cd ../../../
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue_fob[1] --pciaddr=01:00.0
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue[1] --pciaddr=10.24.48.17
    - sudo python3 -B -m pytest scripts/driver_test.py --pciaddr=01:00.0  # python space driver
    - cd src; make unittest

stress_test:
  only:
    - schedules
  artifacts:
    paths:
      - test.log
    when: always
    expire_in: 5 yrs
  script:
    - make test
    - cat test.log | grep "480 passed in" || exit -1

scripts_test:
  only:
    - web
  artifacts:
    paths:
      - test.log
      - performance_report.xlsx
    when: always
    expire_in: 5 yrs
  script:
    - make test TESTS=scripts/$SCRIPT_PATH
