variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GET_SOURCES_ATTEMPTS: 3

default:
  before_script:
    - echo $TESTS
    - echo $pciaddr
    - ./install.sh
  after_script:
    - make reset
    - make clean
  
checkin_test:
  only:
    - pushes
  script:
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue_fob --pciaddr=3d:00.0
    - make setup memsize=4000
    - make nvmt
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue[1] --pciaddr=127.0.0.1
    - cd src; make unittest; cd ..
    - make setup memsize=0

stress_test:
  only:
    - schedules
  script:
    - make test
    - cat test_*.log | grep "3 failed, 389 passed" || exit -1
    - make setup memsize=4000
    - make nvmt
    - make test TESTS=driver_test_tcp.py
    - make setup memsize=0

scripts_test:
  only:
    - web
  artifacts:
    paths:
      - .*_report.xlsx
      - .*_report.pdf
    when: always
    expire_in: 5 yrs
  script:
    - make test pciaddr=$pciaddr TESTS=$TESTS
    - make setup memsize=0
